'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { getGlobalTrendsAction, ingestPublicTrendAction } from '@/app/actions/news-ai';
import { Globe, Zap, ArrowUpRight, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

export function LiveNewsPulse() {
    const [trends, setTrends] = useState<{ title: string; category: string; source_url?: string; slug?: string; original_slug?: string }[]>([]);
    const [currentIndex, setCurrentIndex] = useState(0);
    const [isIngesting, setIsIngesting] = useState(false);
    const router = useRouter();

    useEffect(() => {
        const fetch = async () => {
            const { data } = await getGlobalTrendsAction();
            if (data && data.length > 0) {
                setTrends(data.slice(0, 10));
            }
        };
        fetch();
        const interval = setInterval(fetch, 300000); // Refresh every 5 mins
        return () => clearInterval(interval);
    }, []);

    useEffect(() => {
        if (trends.length === 0) return;
        const interval = setInterval(() => {
            setCurrentIndex((prev) => (prev + 1) % trends.length);
        }, 8000); // Rotate every 8s
        return () => clearInterval(interval);
    }, [trends]);

    if (trends.length === 0) return null;

    const currentTrend = trends[currentIndex];

    const handleReadClick = async (e: React.MouseEvent) => {
        e.preventDefault();
        if (isIngesting || !currentTrend) return;
        setIsIngesting(true);
        try {
            // Already has an internal slug (previously ingested or generated by action)
            // But we still call ingestPublicTrendAction to ensure the article ACTUALLY exists in DB
            const { data, error } = await ingestPublicTrendAction({
                title: currentTrend.title,
                category: currentTrend.category as any,
                source_url: currentTrend.source_url
            });
            if (data?.slug) {
                router.push(`/news/${data.slug}`);
            } else if (error) {
                // Alert the user if the AI or DB ingestion failed (e.g. OpenAI Quota limits)
                alert(`Ingestion failed: ${error}`);
            } else {
                alert('Ingestion failed due to an unknown error.');
            }
        } catch (error) {
            console.error('Ingestion failed:', error);
            alert('A critical error occurred while trying to generate the article.');
        } finally {
            setIsIngesting(false);
        }
    };

    return (
        <div className="w-full bg-[#fdfdfc]/80 dark:bg-slate-950/80 backdrop-blur-2xl border-y border-slate-200/50 dark:border-white/5 py-3 px-4 overflow-hidden relative z-50">
            <div className="container mx-auto flex flex-col md:flex-row items-center gap-6">
                <div className="flex items-center gap-3 shrink-0">
                    <div className="flex -space-x-2">
                        <div className="w-6 h-6 rounded-full bg-red-700 border-2 border-black flex items-center justify-center">
                            <Zap size={10} className="text-white fill-white" />
                        </div>
                    </div>
                    <span className="text-[10px] font-black uppercase tracking-[0.25em] text-red-600 dark:text-red-500 whitespace-nowrap uhd-text-shadow">
                        Global Intelligence Flux
                    </span>
                    <div className="w-px h-4 bg-white/10 hidden md:block" />
                </div>

                <div className="flex-1 w-full overflow-hidden">
                    <AnimatePresence mode="wait">
                        <motion.div
                            key={currentIndex}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -20 }}
                            transition={{ duration: 0.5, ease: "easeOut" }}
                            className="flex items-center justify-between w-full gap-4"
                        >
                            <div className="flex items-center gap-4 overflow-hidden">
                                <span className="text-[9px] font-black uppercase px-2.5 py-1 bg-red-600/10 text-red-600 dark:text-red-500 border border-red-600/20 rounded-lg shadow-sm">
                                    {currentTrend.category}
                                </span>
                                <h4 className="text-xs sm:text-sm font-black text-slate-900 dark:text-white/90 truncate hover:text-red-600 dark:hover:text-red-400 transition-colors cursor-default tracking-tight">
                                    {currentTrend.title}
                                </h4>
                            </div>

                            <div className="flex items-center gap-6 shrink-0">
                                <div className="hidden sm:flex items-center gap-2">
                                    <div className="w-1 h-1 bg-green-500 rounded-full animate-pulse" />
                                    <span className="text-[8px] font-medium text-slate-500 uppercase tracking-widest">Global Data Sync...</span>
                                </div>
                                {currentTrend.slug && (
                                    <button
                                        onClick={handleReadClick}
                                        disabled={isIngesting}
                                        className="text-slate-400 dark:text-white/40 hover:text-red-600 dark:hover:text-red-500 transition-all flex items-center gap-2 group disabled:opacity-50 disabled:cursor-not-allowed bg-slate-100 dark:bg-white/5 px-3 py-1.5 rounded-lg border border-slate-200 dark:border-white/10"
                                    >
                                        <span className="text-[9px] font-black uppercase tracking-tighter">
                                            {isIngesting ? 'Syncing...' : 'Deploy Analysis'}
                                        </span>
                                        {isIngesting ? <Loader2 size={12} className="animate-spin" /> : <Zap size={12} className="fill-red-500 text-red-500" />}
                                    </button>
                                )}
                            </div>
                        </motion.div>
                    </AnimatePresence>
                </div>
            </div>

            {/* Ambient Progress Bar */}
            <motion.div
                key={`progress-${currentIndex}`}
                initial={{ scaleX: 0 }}
                animate={{ scaleX: 1 }}
                transition={{ duration: 8, ease: "linear" }}
                className="absolute bottom-0 left-0 h-[1px] bg-red-700 origin-left w-full"
            />
        </div>
    );
}
