'use client';

import { useState, useCallback, useEffect, useMemo } from 'react';
import Image from 'next/image';
import { useRouter } from '@/lib/navigation';
import { Button } from '@/components/ui/Button';
import { TipTapEditor } from '@/components/editor/TipTapEditor';
import {
    Save,
    ArrowLeft,
    Eye,
    Brain,
    PenTool,
    FileText,
    Zap,
    Layout,
    ChevronRight,
    Globe,
    Tag,
    Image as ImageIcon,
    CheckCircle2,
    AlertTriangle,
    Timer,
    Target
} from 'lucide-react';
import { MediaUploader } from '@/components/media/MediaUploader';
import { createNews, updateNews } from '@/app/actions/news';
import { getNewsDraftAction, getContextBriefAction, getEditorialStrategyAction } from '@/app/actions/news-ai';
import { NewsDraftResult, ContextBriefResult, EditorialStrategyResult } from '@/lib/ai/news-ai';

interface NewsEditorProps {
    initialData?: any;
    mode: 'create' | 'edit';
}

const DEFAULT_COUNTRIES = ['Global', 'Nepal', 'India', 'USA', 'UK', 'China', 'Japan', 'Australia'];
const DEFAULT_CATEGORIES = ['World', 'Politics', 'Business', 'Tech', 'Culture', 'Science', 'Opinion', 'Sports', 'Health', 'Style'];

export function NewsEditor({ initialData, mode }: NewsEditorProps) {
    const router = useRouter();
    const draftStorageKey = 'terai-news-studio-draft-v1';
    const [isSaving, setIsSaving] = useState(false);
    const [isAnalyzing, setIsAnalyzing] = useState(false);
    const [editorialMode, setEditorialMode] = useState<'manuscript' | 'intelligence'>('manuscript');
    const [aiDraft, setAiDraft] = useState<NewsDraftResult | null>(null);
    const [aiContext, setAiContext] = useState<ContextBriefResult | null>(null);
    const [aiStrategy, setAiStrategy] = useState<EditorialStrategyResult | null>(null);

    // Form States
    const [title, setTitle] = useState(initialData?.title || '');
    const [summary, setSummary] = useState(initialData?.summary || '');
    const [content, setContent] = useState(initialData?.content || '');
    const [tags, setTags] = useState<string[]>(initialData?.tags || []);
    const [currentTag, setCurrentTag] = useState('');
    const [country, setCountry] = useState(initialData?.country || 'Global');
    const [category, setCategory] = useState(initialData?.category || 'World');
    const [extraCountries, setExtraCountries] = useState<string[]>([]);
    const [extraCategories, setExtraCategories] = useState<string[]>([]);
    const [newCountry, setNewCountry] = useState('');
    const [newCategory, setNewCategory] = useState('');
    const [coverImage, setCoverImage] = useState(initialData?.cover_image || '');
    const [isGeneratingCover, setIsGeneratingCover] = useState(false);
    const [autoGeneratedOnce, setAutoGeneratedOnce] = useState(false);

    useEffect(() => {
        const run = async () => {
            if (coverImage) return;
            if (!title?.trim()) return;
            if (isGeneratingCover) return;
            if (autoGeneratedOnce) return;
            setIsGeneratingCover(true);
            try {
                const res = await fetch('/api/admin/news/generate-thumbnail', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ title, summary })
                });
                if (res.ok) {
                    const data = await res.json();
                    if (data?.url) {
                        setCoverImage(data.url);
                        setAutoGeneratedOnce(true);
                    }
                }
            } catch {}
            setIsGeneratingCover(false);
        };
        run();
    }, [title, summary, coverImage, isGeneratingCover, autoGeneratedOnce]);

    useEffect(() => {
        if (mode !== 'create') return;
        if (typeof window === 'undefined') return;
        const raw = window.localStorage.getItem(draftStorageKey);
        if (!raw) return;
        try {
            const saved = JSON.parse(raw);
            if (!saved) return;
            if (!title && saved.title) setTitle(saved.title);
            if (!summary && saved.summary) setSummary(saved.summary);
            if (!content && saved.content) setContent(saved.content);
            if (!coverImage && saved.coverImage) setCoverImage(saved.coverImage);
            if ((!tags || tags.length === 0) && Array.isArray(saved.tags)) setTags(saved.tags.slice(0, 12));
            if (saved.country) setCountry(saved.country);
            if (saved.category) setCategory(saved.category);
        } catch {
            window.localStorage.removeItem(draftStorageKey);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [mode]);

    useEffect(() => {
        if (mode !== 'create') return;
        if (typeof window === 'undefined') return;
        const payload = {
            title,
            summary,
            content,
            tags,
            country,
            category,
            coverImage,
            savedAt: Date.now(),
        };
        window.localStorage.setItem(draftStorageKey, JSON.stringify(payload));
    }, [mode, title, summary, content, tags, country, category, coverImage, draftStorageKey]);

    const isSensitiveTopic = useCallback(() => {
        const sensitiveKeywords = ['politics', 'health', 'conflict', 'war', 'election', 'medical', 'security', 'crisis', 'intelligence'];
        return sensitiveKeywords.some(key =>
            title.toLowerCase().includes(key) ||
            category.toLowerCase().includes(key) ||
            summary.toLowerCase().includes(key)
        );
    }, [title, category, summary]);

    const handleGenerateDraft = async () => {
        if (!title && editorialMode === 'intelligence') {
            alert('Please enter a topic or tentative headline first.');
            return;
        }
        setIsAnalyzing(true);
        try {
            const { data, error } = await getNewsDraftAction({
                topic: title,
                region: country,
                tone: 'Analytical',
                depth: 'Standard'
            });
            if (data) {
                setAiDraft(data);
                // We don't auto-apply! Human-in-the-loop.
            } else if (error) {
                alert(error);
            }
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handleGenerateBrief = async () => {
        setIsAnalyzing(true);
        try {
            const { data } = await getContextBriefAction(title);
            if (data) setAiContext(data);
        } finally {
            setIsAnalyzing(false);
        }
    };

    const handleGenerateStrategy = async () => {
        setIsAnalyzing(true);
        try {
            const { data } = await getEditorialStrategyAction(content, title);
            if (data) setAiStrategy(data);
        } finally {
            setIsAnalyzing(false);
        }
    };

    const applyDraft = () => {
        if (!aiDraft) return;
        setTitle(aiDraft.print_headline);
        setSummary(aiDraft.executive_summary);
        setContent(aiDraft.body);
    };

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setIsSaving(true);

        const formData = new FormData(e.currentTarget);
        formData.set('title', title);
        formData.set('summary', summary);
        formData.set('content', content);
        formData.set('tags', tags.join(','));
        formData.set('country', country);
        formData.set('category', category);
        if (!coverImage) {
            try {
                const res = await fetch('/api/admin/news/generate-thumbnail', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ title, summary })
                });
                if (res.ok) {
                    const data = await res.json();
                    if (data?.url) {
                        setCoverImage(data.url);
                    }
                }
            } catch {}
        }
        formData.set('cover_image', coverImage || '');

        try {
            let result: any;
            if (mode === 'create') {
                result = await createNews(formData);
            } else {
                result = await updateNews(initialData.id, formData);
            }
            if (result?.error) {
                alert(result.error);
            } else {
                if (mode === 'create' && typeof window !== 'undefined') {
                    window.localStorage.removeItem(draftStorageKey);
                }
                router.push('/admin/studio/news');
            }
        } catch (err: any) {
            console.error(err);
            alert('Failed to save');
        } finally {
            setIsSaving(false);
        }
    };

    const addTag = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && currentTag.trim()) {
            e.preventDefault();
            if (!tags.includes(currentTag.trim())) {
                setTags([...tags, currentTag.trim()]);
            }
            setCurrentTag('');
        }
    };

    const addCustomCountry = () => {
        const next = newCountry.trim();
        if (!next) return;
        if (!countryOptions.includes(next)) {
            setExtraCountries((prev) => [...prev, next]);
        }
        setCountry(next);
        setNewCountry('');
    };

    const addCustomCategory = () => {
        const next = newCategory.trim();
        if (!next) return;
        if (!categoryOptions.includes(next)) {
            setExtraCategories((prev) => [...prev, next]);
        }
        setCategory(next);
        setNewCategory('');
    };

    const plainText = useMemo(
        () => (content || '').replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim(),
        [content]
    );
    const wordCount = useMemo(() => (plainText ? plainText.split(' ').length : 0), [plainText]);
    const readingMinutes = useMemo(() => Math.max(1, Math.ceil(wordCount / 220)), [wordCount]);

    const headlineLength = title.trim().length;
    const summaryLength = summary.trim().length;
    const hasCover = Boolean(coverImage.trim());
    const hasTags = tags.length >= 3;
    const hasDepth = wordCount >= 400;
    const seoHeadlineRange = headlineLength >= 42 && headlineLength <= 78;
    const seoSummaryRange = summaryLength >= 120 && summaryLength <= 220;

    const scoreItems = [
        { ok: seoHeadlineRange, weight: 20 },
        { ok: seoSummaryRange, weight: 20 },
        { ok: hasCover, weight: 15 },
        { ok: hasTags, weight: 15 },
        { ok: hasDepth, weight: 20 },
        { ok: !!category && !!country, weight: 10 },
    ];
    const qualityScore = Math.round(scoreItems.reduce((acc, item) => acc + (item.ok ? item.weight : 0), 0));
    const countryOptions = useMemo(
        () => Array.from(new Set([...DEFAULT_COUNTRIES, ...extraCountries, country].filter(Boolean))),
        [country, extraCountries]
    );
    const categoryOptions = useMemo(
        () => Array.from(new Set([...DEFAULT_CATEGORIES, ...extraCategories, category].filter(Boolean))),
        [category, extraCategories]
    );

    return (
        <form onSubmit={handleSubmit} className="min-h-screen bg-[#fdfdfc] pb-20 news-paper-theme text-slate-900 relative">
            {isAnalyzing && (
                <div className="fixed inset-0 z-[100] bg-white/40 backdrop-blur-[2px] flex items-center justify-center pointer-events-none">
                    <div className="bg-white border border-slate-200 shadow-2xl rounded-3xl p-8 flex flex-col items-center gap-4 animate-in fade-in zoom-in duration-300">
                        <div className="relative">
                            <Brain className="w-12 h-12 text-red-700 animate-pulse" />
                            <div className="absolute -inset-4 bg-red-100/30 rounded-full animate-ping" />
                        </div>
                        <span className="text-xs font-black uppercase tracking-[0.3em] text-slate-400">Analyzing Editorial Intelligence...</span>
                    </div>
                </div>
            )}

            {/* Top Bar */}
            <div className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-slate-200 px-6 py-4 flex items-center justify-between">
                <div className="flex items-center gap-4">
                    <Button type="button" variant="ghost" size="sm" onClick={() => router.back()} className="text-slate-600 hover:text-red-700">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back
                    </Button>
                    <div className="h-6 w-px bg-slate-200" />

                    {/* Mode Switcher */}
                    <div className="flex bg-slate-100 p-1 rounded-xl">
                        <button
                            type="button"
                            onClick={() => setEditorialMode('manuscript')}
                            className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${editorialMode === 'manuscript' ? 'bg-white shadow-sm text-slate-900' : 'text-slate-400 hover:text-slate-600'}`}
                        >
                            <PenTool size={12} />
                            Manuscript
                        </button>
                        <button
                            type="button"
                            onClick={() => setEditorialMode('intelligence')}
                            className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest transition-all ${editorialMode === 'intelligence' ? 'bg-white shadow-sm text-red-700' : 'text-slate-400 hover:text-slate-600'}`}
                        >
                            <Brain size={12} />
                            Intelligence
                        </button>
                    </div>

                    <div className="h-6 w-px bg-slate-200 ml-2" />
                    <span className="text-sm font-black uppercase tracking-widest text-slate-400">
                        {mode === 'create' ? 'Intelligence Creation' : 'Intelligence Refinement'}
                    </span>
                    {isSaving && <span className="text-[10px] font-black uppercase text-red-600 animate-pulse ml-4 tracking-widest">Transmitting...</span>}
                </div>
                <div className="flex items-center gap-2">
                    <select
                        name="status"
                        defaultValue={initialData?.status || 'draft'}
                        className="bg-slate-50 border border-slate-200 rounded-lg px-3 py-2 text-xs font-black uppercase tracking-widest focus:ring-2 focus:ring-red-500 outline-none text-slate-600"
                    >
                        <option value="draft">Draft Status</option>
                        <option value="published">Lead Publication</option>
                    </select>
                    <Button type="submit" disabled={isSaving} className="bg-red-700 hover:bg-black text-white px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all shadow-lg shadow-red-500/10">
                        <Save className="w-4 h-4 mr-2" />
                        {isSaving ? 'Encrypting...' : 'Save Intel'}
                    </Button>
                </div>
            </div>

            <div className={`max-w-[1800px] mx-auto grid grid-cols-1 ${editorialMode === 'intelligence' ? 'lg:grid-cols-[1fr,450px,350px]' : 'lg:grid-cols-[1fr,400px]'} transition-all duration-500 gap-8 p-8`}>
                {/* Main Editor */}
                <div className="space-y-6">
                    <div className="bg-white rounded-[2rem] p-10 border border-slate-100 shadow-sm space-y-6">
                        <div className="group relative aspect-[21/9] bg-slate-50 rounded-2xl overflow-hidden border-2 border-dashed border-slate-200 hover:border-red-200 transition-colors">
                            {coverImage ? (
                                <>
                                    <Image 
                                        src={coverImage} 
                                        alt="Cover" 
                                        fill
                                        className="object-cover"
                                    />
                                    {isGeneratingCover && (
                                        <div className="absolute inset-0 flex items-center justify-center bg-black/20">
                                            <span className="text-[10px] font-black uppercase tracking-widest text-white">Generating Visual</span>
                                        </div>
                                    )}
                                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4 z-10">
                                        <MediaUploader
                                            onUploadComplete={(url) => setCoverImage(url)}
                                            label="Change Cover Image"
                                            variant="button"
                                            className="bg-white text-slate-900 hover:bg-slate-100"
                                        />
                                        <Button 
                                            type="button" 
                                            variant="destructive" 
                                            size="sm"
                                            onClick={() => setCoverImage('')}
                                        >
                                            Remove
                                        </Button>
                                    </div>
                                </>
                            ) : (
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <MediaUploader
                                        onUploadComplete={(url) => setCoverImage(url)}
                                        label="Upload Cover Image"
                                        variant="dropzone"
                                        className="border-none w-full h-full flex items-center justify-center"
                                    />
                                </div>
                            )}
                        </div>

                        <input
                            name="title"
                            value={title}
                            onChange={(e) => setTitle(e.target.value)}
                            placeholder="Primary Headline"
                            required
                            className="w-full text-4xl md:text-5xl font-serif font-black bg-transparent border-none p-0 placeholder:text-slate-200 focus:ring-0 text-slate-900"
                        />
                        <textarea
                            name="summary"
                            value={summary}
                            onChange={(e) => setSummary(e.target.value)}
                            placeholder="Executive Summary (SEO Narrative)..."
                            className="w-full min-h-[120px] text-lg text-slate-500 font-serif leading-relaxed bg-transparent border-none p-0 resize-none focus:ring-0"
                        />
                    </div>

                    <div className="bg-white rounded-[2rem] border border-slate-100 shadow-sm min-h-[600px] overflow-hidden">
                        <TipTapEditor value={content} onChange={setContent} />
                    </div>
                </div>

                {/* Intelligence Hub Overlay */}
                {editorialMode === 'intelligence' && (
                    <div className="space-y-6 animate-in slide-in-from-right-4 duration-500">
                        <div className="bg-white rounded-[2rem] border-2 border-red-50 p-8 space-y-8 sticky top-24 min-h-[85vh] shadow-xl shadow-red-500/5">
                            <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-red-700 flex items-center gap-2">
                                    <Brain size={14} /> Intelligence Hub
                                </span>
                                <span className="text-[9px] font-black uppercase tracking-widest text-slate-300">Refectl Agency v4.2</span>
                            </div>

                            {/* Sensitivity Flag */}
                            {isSensitiveTopic() && (
                                <div className="p-4 bg-red-50 border border-red-100 rounded-xl animate-in fade-in slide-in-from-top-2 duration-300">
                                    <div className="flex items-center gap-2 text-red-700 mb-1">
                                        <Eye size={12} className="animate-pulse" />
                                        <span className="text-[9px] font-black uppercase tracking-widest">Extra Review Recommended</span>
                                    </div>
                                    <p className="text-[8px] text-red-600/70 font-bold uppercase tracking-widest leading-relaxed">
                                        High-stakes topic detected. AI assistance requires rigorous human verification for accuracy and bias.
                                    </p>
                                </div>
                            )}

                            {/* Intelligence Tabs/Sections */}
                            <div className="space-y-8 overflow-y-auto max-h-[calc(100vh-250px)] pr-2 no-scrollbar">
                                {/* Draft Synthesis */}
                                <div className="space-y-4">
                                    <div className="flex items-center justify-between">
                                        <h4 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
                                            <Zap size={12} className="text-red-700" /> Draft Synthesis
                                        </h4>
                                        <Button type="button" size="sm" onClick={handleGenerateDraft} className="h-7 text-[9px] bg-slate-900 hover:bg-red-700">Synthesize</Button>
                                    </div>
                                    {aiDraft ? (
                                        <div className="bg-slate-50 rounded-xl p-4 border border-slate-100 space-y-3">
                                            <p className="text-[11px] font-serif italic text-slate-600 leading-relaxed line-clamp-3">"{aiDraft.subheadline}"</p>
                                            <Button type="button" onClick={applyDraft} variant="outline" className="w-full text-[9px] font-black uppercase tracking-widest h-8 border-red-100 text-red-700 hover:bg-red-50">Apply to Manuscript</Button>
                                        </div>
                                    ) : (
                                        <div className="bg-slate-50/50 rounded-xl border border-dashed border-slate-200 p-6 text-center">
                                            <p className="text-[9px] font-black uppercase tracking-widest text-slate-300">Ready for Synthesis</p>
                                        </div>
                                    )}
                                </div>

                                {/* Context Brief */}
                                <div className="space-y-4">
                                    <div className="flex items-center justify-between">
                                        <h4 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
                                            <FileText size={12} className="text-red-700" /> Context Brief
                                        </h4>
                                        <Button type="button" size="sm" onClick={handleGenerateBrief} variant="ghost" className="h-7 text-[9px] text-slate-400 hover:text-red-700">Retrieve Brief</Button>
                                    </div>
                                    {aiContext && (
                                        <div className="space-y-4">
                                            <div className="bg-slate-50 rounded-xl p-4 border border-slate-100">
                                                <span className="text-[8px] font-black uppercase text-slate-400 block mb-1">Analytic Background</span>
                                                <p className="text-[10px] text-slate-600 leading-relaxed font-serif">{aiContext.background}</p>
                                            </div>
                                            <div className="bg-slate-50 rounded-xl p-4 border border-slate-100">
                                                <span className="text-[8px] font-black uppercase text-slate-400 block mb-1">Key Stakeholders</span>
                                                <p className="text-[10px] text-slate-600 leading-relaxed font-serif whitespace-pre-wrap">{aiContext.key_players}</p>
                                            </div>
                                        </div>
                                    )}
                                </div>

                                {/* Editorial Strategy */}
                                <div className="space-y-4 border-t border-slate-100 pt-8">
                                    <div className="flex items-center justify-between">
                                        <h4 className="text-[11px] font-black uppercase tracking-widest text-slate-500 flex items-center gap-2">
                                            <Layout size={12} className="text-red-700" /> Editorial Strategy
                                        </h4>
                                        <Button type="button" size="sm" onClick={handleGenerateStrategy} variant="ghost" className="h-7 text-[9px] text-slate-400 hover:text-red-700">Analyze Manuscript</Button>
                                    </div>

                                    {aiStrategy ? (
                                        <div className="space-y-3">
                                            <div className="p-4 bg-slate-50 rounded-xl border border-slate-100">
                                                <span className="text-[8px] font-black uppercase text-slate-400 block mb-1">Optimized Summary</span>
                                                <p className="text-[10px] text-slate-600 font-serif line-clamp-2">{aiStrategy.editorial_summary}</p>
                                                <button type="button" onClick={() => setSummary(aiStrategy.editorial_summary)} className="text-[8px] font-black uppercase text-red-700 mt-2 flex items-center gap-1 hover:underline">Apply Summary <ChevronRight size={8} /></button>
                                            </div>
                                            <div className="p-4 bg-slate-50 rounded-xl border border-slate-100">
                                                <span className="text-[8px] font-black uppercase text-slate-400 block mb-1">Operational Tags</span>
                                                <div className="flex flex-wrap gap-1 mt-1">
                                                    {aiStrategy.operational_tags.map(t => (
                                                        <button
                                                            key={t}
                                                            type="button"
                                                            onClick={() => !tags.includes(t) && setTags([...tags, t])}
                                                            className="px-2 py-0.5 bg-white border border-slate-200 rounded text-[8px] font-bold text-slate-500 hover:border-red-700 transition-colors"
                                                        >
                                                            + {t}
                                                        </button>
                                                    ))}
                                                </div>
                                            </div>
                                            {/* Headline Lab */}
                                            <div className="p-4 bg-slate-50 rounded-xl border border-slate-100">
                                                <span className="text-[8px] font-black uppercase text-slate-400 block mb-2">Headline Lab</span>
                                                <div className="space-y-2">
                                                    <div className="flex flex-col gap-1">
                                                        <span className="text-[7px] font-black uppercase text-slate-300">Print Tradition</span>
                                                        <p className="text-[10px] text-slate-900 font-serif font-bold cursor-pointer hover:text-red-700" onClick={() => setTitle(aiStrategy.headline_variants.print)}>{aiStrategy.headline_variants.print}</p>
                                                    </div>
                                                    <div className="flex flex-col gap-1">
                                                        <span className="text-[7px] font-black uppercase text-slate-300">Digital Variant</span>
                                                        <p className="text-[10px] text-slate-900 font-serif font-bold cursor-pointer hover:text-red-700" onClick={() => setTitle(aiStrategy.headline_variants.digital)}>{aiStrategy.headline_variants.digital}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    ) : (
                                        <div className="bg-slate-50/50 rounded-xl border border-dashed border-slate-200 p-6 text-center">
                                            <p className="text-[9px] font-black uppercase tracking-widest text-slate-300 italic">Manuscript Analysis Required</p>
                                        </div>
                                    )}
                                </div>
                            </div>

                            {/* AI Disclaimer */}
                            <div className="absolute bottom-6 left-8 right-8 py-4 border-t border-slate-100">
                                <span className="text-[8px] font-black uppercase text-slate-300 tracking-widest flex items-center gap-1.5">
                                    <div className="w-1 h-1 bg-red-700 rounded-full" /> AI-Assisted Draft Mode
                                </span>
                                <p className="text-[7px] text-slate-400 mt-1 uppercase tracking-widest font-bold">Human verification mandatory before publication</p>
                            </div>
                        </div>
                    </div>
                )}

                {/* Sidebar */}
                <div className="space-y-6">
                    {/* Metadata Card */}
                    <div className="bg-slate-50 rounded-[2rem] border border-slate-200 p-8 space-y-8 sticky top-24">
                        <div className="space-y-4">
                            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                <ImageIcon className="w-3 h-3 text-red-700" /> Visual Assertion
                            </label>
                            <div className="relative group cursor-pointer bg-white border-2 border-dashed border-slate-200 rounded-2xl p-6 text-center hover:border-red-700 transition-colors">
                                <input
                                    type="text"
                                    name="cover_image"
                                    value={coverImage}
                                    onChange={(e) => setCoverImage(e.target.value)}
                                    placeholder="Image Asset URL"
                                    className="w-full bg-transparent text-[11px] font-bold text-center outline-none text-slate-900"
                                />
                                <p className="text-[9px] font-black uppercase tracking-widest text-slate-300 mt-2">Optimal Archive: 1200x630</p>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                <Globe className="w-3 h-3 text-red-700" /> Regional Scope
                            </label>
                            <input
                                name="country"
                                value={country}
                                onChange={(e) => setCountry(e.target.value)}
                                list="country-options"
                                placeholder="Select or type country"
                                className="w-full px-4 py-3 rounded-xl bg-white border border-slate-200 text-xs font-bold focus:ring-2 focus:ring-red-500 outline-none text-slate-900"
                            />
                            <datalist id="country-options">
                                {countryOptions.map((c) => (
                                    <option key={c} value={c} />
                                ))}
                            </datalist>
                            <div className="flex gap-2">
                                <input
                                    value={newCountry}
                                    onChange={(e) => setNewCountry(e.target.value)}
                                    placeholder="Add new country"
                                    className="flex-1 px-3 py-2 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-900"
                                />
                                <Button type="button" onClick={addCustomCountry} variant="ghost" className="border border-slate-200 bg-white text-slate-700 hover:bg-slate-50">
                                    Add
                                </Button>
                            </div>
                            <div className="flex flex-wrap gap-2">
                                {countryOptions.slice(0, 8).map((c) => (
                                    <button
                                        key={c}
                                        type="button"
                                        onClick={() => setCountry(c)}
                                        className={`px-2 py-1 rounded-md text-[10px] font-black uppercase tracking-wider border ${country === c ? 'border-red-400 text-red-700 bg-red-50' : 'border-slate-200 text-slate-500 bg-white'}`}
                                    >
                                        {c}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="space-y-4">
                            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                <Tag className="w-3 h-3 text-red-700" /> Intelligence Pillar
                            </label>
                            <input
                                name="category"
                                value={category}
                                onChange={(e) => setCategory(e.target.value)}
                                list="category-options"
                                placeholder="Select or type category"
                                className="w-full px-4 py-3 rounded-xl bg-white border border-slate-200 text-xs font-bold focus:ring-2 focus:ring-red-500 outline-none text-slate-900"
                            />
                            <datalist id="category-options">
                                {categoryOptions.map((c) => (
                                    <option key={c} value={c} />
                                ))}
                            </datalist>
                            <div className="flex gap-2">
                                <input
                                    value={newCategory}
                                    onChange={(e) => setNewCategory(e.target.value)}
                                    placeholder="Add new category"
                                    className="flex-1 px-3 py-2 rounded-lg bg-white border border-slate-200 text-xs font-bold text-slate-900"
                                />
                                <Button type="button" onClick={addCustomCategory} variant="ghost" className="border border-slate-200 bg-white text-slate-700 hover:bg-slate-50">
                                    Add
                                </Button>
                            </div>
                            <div className="flex flex-wrap gap-2">
                                {categoryOptions.slice(0, 8).map((c) => (
                                    <button
                                        key={c}
                                        type="button"
                                        onClick={() => setCategory(c)}
                                        className={`px-2 py-1 rounded-md text-[10px] font-black uppercase tracking-wider border ${category === c ? 'border-red-400 text-red-700 bg-red-50' : 'border-slate-200 text-slate-500 bg-white'}`}
                                    >
                                        {c}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="flex items-center justify-between p-4 rounded-2xl bg-red-50 border border-red-100">
                            <div className="flex flex-col">
                                <span className="text-[10px] font-black uppercase tracking-widest text-red-700">Trending Pulse</span>
                                <span className="text-[9px] text-red-700/50 font-bold">Mark for prime visibility</span>
                            </div>
                            <input
                                type="checkbox"
                                name="is_trending"
                                value="true"
                                defaultChecked={initialData?.is_trending}
                                className="w-5 h-5 rounded-lg border-red-300 text-red-700 focus:ring-red-500"
                            />
                        </div>

                        <div className="space-y-4">
                            <label className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                <Eye className="w-3 h-3 text-red-700" /> Operational Tags
                            </label>
                            <div className="flex flex-wrap gap-2 mb-2">
                                {tags.map(tag => (
                                    <span key={tag} className="bg-white text-slate-900 px-3 py-1.5 rounded-lg text-[9px] font-black uppercase tracking-widest flex items-center gap-2 border border-slate-200">
                                        {tag}
                                        <button type="button" onClick={() => setTags(tags.filter(t => t !== tag))} className="text-slate-300 hover:text-red-700 transition-colors ml-1">×</button>
                                    </span>
                                ))}
                            </div>
                            <input
                                value={currentTag}
                                onChange={e => setCurrentTag(e.target.value)}
                                onKeyDown={addTag}
                                placeholder="Add identifiers..."
                                className="w-full px-4 py-3 rounded-xl bg-white border border-slate-200 text-xs font-bold text-slate-900"
                            />
                        </div>

                        <div className="space-y-4 border-t border-slate-200 pt-6">
                            <div className="flex items-center justify-between">
                                <span className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                    <Target className="w-3 h-3 text-red-700" /> Publication Readiness
                                </span>
                                <span className={`text-sm font-black ${qualityScore >= 75 ? 'text-emerald-600' : qualityScore >= 50 ? 'text-amber-600' : 'text-red-600'}`}>
                                    {qualityScore}%
                                </span>
                            </div>
                            <div className="h-2 bg-slate-200 rounded-full overflow-hidden">
                                <div
                                    className={`h-full transition-all duration-500 ${qualityScore >= 75 ? 'bg-emerald-500' : qualityScore >= 50 ? 'bg-amber-500' : 'bg-red-500'}`}
                                    style={{ width: `${qualityScore}%` }}
                                />
                            </div>
                            <div className="grid grid-cols-1 gap-2">
                                {[
                                    { label: 'Headline length optimized (42-78 chars)', ok: seoHeadlineRange },
                                    { label: 'Summary depth optimized (120-220 chars)', ok: seoSummaryRange },
                                    { label: 'Cover image attached', ok: hasCover },
                                    { label: 'At least 3 strategic tags', ok: hasTags },
                                    { label: 'Article depth 400+ words', ok: hasDepth },
                                ].map((item) => (
                                    <div key={item.label} className="flex items-center gap-2 text-[10px] font-bold text-slate-600">
                                        {item.ok ? (
                                            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                                        ) : (
                                            <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
                                        )}
                                        <span>{item.label}</span>
                                    </div>
                                ))}
                            </div>
                        </div>

                        <div className="space-y-4 border-t border-slate-200 pt-6">
                            <span className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 flex items-center gap-2">
                                <Timer className="w-3 h-3 text-red-700" /> Writing Analytics
                            </span>
                            <div className="grid grid-cols-3 gap-3">
                                <div className="rounded-xl bg-white border border-slate-200 p-3 text-center">
                                    <p className="text-[9px] uppercase tracking-widest font-black text-slate-400">Words</p>
                                    <p className="text-xl font-black text-slate-900 mt-1">{wordCount}</p>
                                </div>
                                <div className="rounded-xl bg-white border border-slate-200 p-3 text-center">
                                    <p className="text-[9px] uppercase tracking-widest font-black text-slate-400">Read</p>
                                    <p className="text-xl font-black text-slate-900 mt-1">{readingMinutes}m</p>
                                </div>
                                <div className="rounded-xl bg-white border border-slate-200 p-3 text-center">
                                    <p className="text-[9px] uppercase tracking-widest font-black text-slate-400">Tags</p>
                                    <p className="text-xl font-black text-slate-900 mt-1">{tags.length}</p>
                                </div>
                            </div>
                            <div className="rounded-2xl border border-slate-200 bg-white p-4 space-y-2">
                                <p className="text-[9px] font-black uppercase tracking-widest text-slate-400">Search Preview</p>
                                <p className="text-sm font-black text-slate-900 line-clamp-2">{title || 'Headline preview appears here'}</p>
                                <p className="text-[11px] text-slate-500 line-clamp-2">{summary || 'Summary preview appears here'}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    );
}
