// Achievement Definitions - 15 predefined achievements

import { Achievement } from './models/Achievement';

export const ACHIEVEMENT_DEFINITIONS: Achievement[] = [
    // LEARNING CATEGORY (4 achievements)
    {
        id: 'scholars_path',
        name: "Scholar's Path",
        description: 'Complete courses to advance your learning journey',
        icon: '📚',
        category: 'learning',
        type: 'standard',
        isSecret: false,
        rarity: 'common',
        points: 150,
        tiers: [
            {
                level: 1,
                name: 'Bronze Scholar',
                description: 'Complete 5 courses',
                requirement: { type: 'courses_completed', value: 5 },
                xpReward: 100,
                icon: '🥉',
            },
            {
                level: 2,
                name: 'Silver Scholar',
                description: 'Complete 15 courses',
                requirement: { type: 'courses_completed', value: 15 },
                xpReward: 250,
                icon: '🥈',
            },
            {
                level: 3,
                name: 'Gold Scholar',
                description: 'Complete 50 courses',
                requirement: { type: 'courses_completed', value: 50 },
                xpReward: 500,
                icon: '🥇',
            },
        ],
    },
    {
        id: 'knowledge_seeker',
        name: 'Knowledge Seeker',
        description: 'Watch educational videos to expand your knowledge',
        icon: '🎥',
        category: 'learning',
        type: 'standard',
        isSecret: false,
        rarity: 'common',
        points: 120,
        tiers: [
            {
                level: 1,
                name: 'Video Viewer',
                description: 'Watch 20 videos',
                requirement: { type: 'videos_watched', value: 20 },
                xpReward: 75,
            },
            {
                level: 2,
                name: 'Video Enthusiast',
                description: 'Watch 100 videos',
                requirement: { type: 'videos_watched', value: 100 },
                xpReward: 200,
            },
            {
                level: 3,
                name: 'Video Master',
                description: 'Watch 500 videos',
                requirement: { type: 'videos_watched', value: 500 },
                xpReward: 400,
            },
        ],
    },
    {
        id: 'quiz_champion',
        name: 'Quiz Champion',
        description: 'Prove your knowledge by completing quizzes',
        icon: '📝',
        category: 'learning',
        type: 'standard',
        isSecret: false,
        rarity: 'rare',
        points: 200,
        tiers: [
            {
                level: 1,
                name: 'Quiz Novice',
                description: 'Complete 50 quizzes',
                requirement: { type: 'quizzes_completed', value: 50 },
                xpReward: 100,
            },
            {
                level: 2,
                name: 'Quiz Expert',
                description: 'Complete 200 quizzes',
                requirement: { type: 'quizzes_completed', value: 200 },
                xpReward: 250,
            },
            {
                level: 3,
                name: 'Quiz Master',
                description: 'Complete 500 quizzes',
                requirement: { type: 'quizzes_completed', value: 500 },
                xpReward: 500,
            },
            {
                level: 4,
                name: 'Quiz Legend',
                description: 'Complete 1000 quizzes',
                requirement: { type: 'quizzes_completed', value: 1000 },
                xpReward: 1000,
            },
        ],
    },
    {
        id: 'perfect_student',
        name: 'Perfect Student',
        description: 'Achieve perfect scores to show true mastery',
        icon: '💯',
        category: 'learning',
        type: 'standard',
        isSecret: false,
        rarity: 'epic',
        points: 250,
        tiers: [
            {
                level: 1,
                name: 'Perfectionist',
                description: 'Get 10 perfect scores (100%)',
                requirement: { type: 'perfect_scores', value: 10 },
                xpReward: 150,
            },
            {
                level: 2,
                name: 'Elite Student',
                description: 'Get 50 perfect scores',
                requirement: { type: 'perfect_scores', value: 50 },
                xpReward: 350,
            },
            {
                level: 3,
                name: 'Flawless Master',
                description: 'Get 100 perfect scores',
                requirement: { type: 'perfect_scores', value: 100 },
                xpReward: 750,
            },
        ],
    },

    // MASTERY CATEGORY (3 achievements)
    {
        id: 'xp_legend',
        name: 'XP Legend',
        description: 'Accumulate massive amounts of experience points',
        icon: '⚡',
        category: 'mastery',
        type: 'standard',
        isSecret: false,
        rarity: 'epic',
        points: 400,
        tiers: [
            {
                level: 1,
                name: 'XP Collector',
                description: 'Reach 10,000 total XP',
                requirement: { type: 'total_xp', value: 10000 },
                xpReward: 200,
            },
            {
                level: 2,
                name: 'XP Enthusiast',
                description: 'Reach 50,000 total XP',
                requirement: { type: 'total_xp', value: 50000 },
                xpReward: 500,
            },
            {
                level: 3,
                name: 'XP Master',
                description: 'Reach 100,000 total XP',
                requirement: { type: 'total_xp', value: 100000 },
                xpReward: 1000,
            },
            {
                level: 4,
                name: 'XP Legend',
                description: 'Reach 500,000 total XP',
                requirement: { type: 'total_xp', value: 500000 },
                xpReward: 2500,
            },
        ],
    },
    {
        id: 'level_master',
        name: 'Level Master',
        description: 'Climb the levels to reach new heights',
        icon: '🎖️',
        category: 'mastery',
        type: 'standard',
        isSecret: false,
        rarity: 'rare',
        points: 300,
        tiers: [
            {
                level: 1,
                name: 'Rising Star',
                description: 'Reach Level 25',
                requirement: { type: 'level_reached', value: 25 },
                xpReward: 250,
            },
            {
                level: 2,
                name: 'Veteran',
                description: 'Reach Level 50',
                requirement: { type: 'level_reached', value: 50 },
                xpReward: 500,
            },
            {
                level: 3,
                name: 'Champion',
                description: 'Reach Level 100',
                requirement: { type: 'level_reached', value: 100 },
                xpReward: 1500,
            },
        ],
    },
    {
        id: 'subject_expert',
        name: 'Subject Expert',
        description: '??? Unlock by achieving excellence in a subject',
        icon: '🎓',
        category: 'mastery',
        type: 'secret',
        isSecret: true,
        rarity: 'legendary',
        points: 500,
        tiers: [
            {
                level: 1,
                name: 'Subject Specialist',
                description: 'Achieve 90%+ average in one subject',
                requirement: { type: 'subject_average', value: 90 },
                xpReward: 200,
            },
            {
                level: 2,
                name: 'Subject Master',
                description: 'Achieve 95%+ average in one subject',
                requirement: { type: 'subject_average', value: 95 },
                xpReward: 400,
            },
            {
                level: 3,
                name: 'Subject Perfectionist',
                description: 'Get 100% in all quizzes of a subject',
                requirement: { type: 'subject_perfect', value: 1 },
                xpReward: 1000,
            },
        ],
    },

    // SOCIAL CATEGORY (3 achievements)
    {
        id: 'dedication',
        name: 'Dedication',
        description: 'Maintain your study streak for extended periods',
        icon: '🔥',
        category: 'social',
        type: 'standard',
        isSecret: false,
        rarity: 'epic',
        points: 350,
        tiers: [
            {
                level: 1,
                name: 'Committed',
                description: 'Maintain a 30-day streak',
                requirement: { type: 'streak_days', value: 30 },
                xpReward: 150,
            },
            {
                level: 2,
                name: 'Devoted',
                description: 'Maintain a 60-day streak',
                requirement: { type: 'streak_days', value: 60 },
                xpReward: 300,
            },
            {
                level: 3,
                name: 'Unstoppable',
                description: 'Maintain a 100-day streak',
                requirement: { type: 'streak_days', value: 100 },
                xpReward: 600,
            },
            {
                level: 4,
                name: 'Legendary Dedication',
                description: 'Maintain a 365-day streak',
                requirement: { type: 'streak_days', value: 365 },
                xpReward: 2000,
            },
        ],
    },
    {
        id: 'community_helper',
        name: 'Community Helper',
        description: 'Help fellow students in their learning journey',
        icon: '🤝',
        category: 'social',
        type: 'standard',
        isSecret: false,
        rarity: 'rare',
        points: 200,
        tiers: [
            {
                level: 1,
                name: 'Helper',
                description: 'Help 10 students',
                requirement: { type: 'students_helped', value: 10 },
                xpReward: 100,
            },
            {
                level: 2,
                name: 'Mentor',
                description: 'Help 50 students',
                requirement: { type: 'students_helped', value: 50 },
                xpReward: 300,
            },
            {
                level: 3,
                name: 'Community Leader',
                description: 'Help 200 students',
                requirement: { type: 'students_helped', value: 200 },
                xpReward: 800,
            },
        ],
    },
    {
        id: 'social_butterfly',
        name: 'Social Butterfly',
        description: 'Build connections with other learners',
        icon: '🦋',
        category: 'social',
        type: 'standard',
        isSecret: false,
        rarity: 'common',
        points: 100,
        tiers: [
            {
                level: 1,
                name: 'Friend Finder',
                description: 'Add 10 friends',
                requirement: { type: 'friends_count', value: 10 },
                xpReward: 50,
            },
            {
                level: 2,
                name: 'Popular',
                description: 'Add 50 friends',
                requirement: { type: 'friends_count', value: 50 },
                xpReward: 200,
            },
        ],
    },

    // EXPLORATION CATEGORY (3 achievements)
    {
        id: 'badge_collector',
        name: 'Badge Collector',
        description: 'Collect badges by achieving various milestones',
        icon: '🎖️',
        category: 'exploration',
        type: 'standard',
        isSecret: false,
        rarity: 'rare',
        points: 180,
        tiers: [
            {
                level: 1,
                name: 'Badge Hunter',
                description: 'Earn 5 badges',
                requirement: { type: 'badges_earned', value: 5 },
                xpReward: 100,
            },
            {
                level: 2,
                name: 'Badge Master',
                description: 'Earn all 10 badges',
                requirement: { type: 'badges_earned', value: 10 },
                xpReward: 500,
            },
            {
                level: 3,
                name: 'Elite Collector',
                description: 'Earn all rare+ badges',
                requirement: { type: 'badges_rare_plus', value: 1 },
                xpReward: 300,
            },
        ],
    },
    {
        id: 'quest_warrior',
        name: 'Quest Warrior',
        description: 'Complete daily quests consistently',
        icon: '⚔️',
        category: 'exploration',
        type: 'standard',
        isSecret: false,
        rarity: 'rare',
        points: 220,
        tiers: [
            {
                level: 1,
                name: 'Quest Beginner',
                description: 'Complete 30 daily quests',
                requirement: { type: 'daily_quests_completed', value: 30 },
                xpReward: 150,
            },
            {
                level: 2,
                name: 'Quest Veteran',
                description: 'Complete 100 daily quests',
                requirement: { type: 'daily_quests_completed', value: 100 },
                xpReward: 400,
            },
            {
                level: 3,
                name: 'Quest Champion',
                description: 'Complete 365 daily quests',
                requirement: { type: 'daily_quests_completed', value: 365 },
                xpReward: 1000,
            },
        ],
    },
    {
        id: 'course_explorer',
        name: 'Course Explorer',
        description: 'Explore different subjects and topics',
        icon: '🗺️',
        category: 'exploration',
        type: 'standard',
        isSecret: false,
        rarity: 'common',
        points: 120,
        tiers: [
            {
                level: 1,
                name: 'Curious Mind',
                description: 'Try 10 different subjects',
                requirement: { type: 'subjects_explored', value: 10 },
                xpReward: 100,
            },
            {
                level: 2,
                name: 'Renaissance Learner',
                description: 'Try 20 different subjects',
                requirement: { type: 'subjects_explored', value: 20 },
                xpReward: 300,
            },
        ],
    },

    // SPECIAL CATEGORY (2 achievements)
    {
        id: 'early_adopter',
        name: 'Early Adopter',
        description: '??? A special reward for pioneers',
        icon: '🌟',
        category: 'special',
        type: 'secret',
        isSecret: true,
        rarity: 'legendary',
        points: 1000,
        tiers: [
            {
                level: 1,
                name: 'Pioneer',
                description: 'Join within the first month of launch',
                requirement: { type: 'days_since_launch', value: 30 },
                xpReward: 500,
            },
        ],
    },
    {
        id: 'perfectionist',
        name: 'The Perfectionist',
        description: '??? The ultimate achievement',
        icon: '👑',
        category: 'special',
        type: 'secret',
        isSecret: true,
        rarity: 'legendary',
        points: 2000,
        tiers: [
            {
                level: 1,
                name: 'Completionist',
                description: 'Complete 100% profile + All achievements',
                requirement: { type: 'all_achievements', value: 1 },
                xpReward: 1000,
            },
        ],
    },
];
